
import { Patient, User, Language } from './types';

// Hardcoded Users for Auth
export const USERS: Record<string, User & { password: string }> = {
  'doctor@medflow.ai': {
    name: 'Dr. Aditi Verma',
    email: 'doctor@medflow.ai',
    password: 'doctor123',
    role: 'doctor',
    avatar: 'https://picsum.photos/id/64/200/200',
  },
  'nurse@medflow.ai': {
    name: 'Nurse Meera Nair',
    email: 'nurse@medflow.ai',
    password: 'nurse123',
    role: 'nurse',
    avatar: 'https://picsum.photos/id/65/200/200',
  },
  'intern@medflow.ai': {
    name: 'Intern Vikram Malhotra',
    email: 'intern@medflow.ai',
    password: 'intern123',
    role: 'intern',
    avatar: 'https://picsum.photos/id/1005/200/200',
  },
  'receptionist@medflow.ai': {
    name: 'Riya Kapoor',
    email: 'receptionist@medflow.ai',
    password: 'receptionist123',
    role: 'receptionist',
    avatar: 'https://picsum.photos/id/342/200/200',
  },
  'cleaner@medflow.ai': {
    name: 'Amit Yadav',
    email: 'cleaner@medflow.ai',
    password: 'cleaner123',
    role: 'cleaner',
    avatar: 'https://picsum.photos/id/447/200/200',
  },
};

// Initial Mock Patients
export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'P-101',
    name: 'Rajesh Kumar',
    age: 45,
    gender: 'Male',
    phone: '555-0123',
    complaints: [{ symptom: 'Chest pain', duration: 1, unit: 'Hours' }],
    severity: 'emergency',
    suggestedDepartment: 'Cardiology',
    aiSummary: 'Patient reports acute substernal chest pain radiating to left arm. High probability of myocardial infarction. Immediate ECG and Troponin levels recommended.',
    status: 'waiting',
    notes: ['Vitals checked: BP 150/95', 'Awaiting ECG result'],
    admittedDate: new Date().toISOString(),
    allergies: ['Penicillin', 'Peanuts'],
    followUp: { date: new Date(Date.now() + 86400000).toISOString(), status: 'scheduled', type: 'urgent' }
  },
  {
    id: 'P-102',
    name: 'Anjali Sharma',
    age: 72,
    gender: 'Female',
    phone: '555-0124',
    complaints: [{ symptom: 'Dizziness', duration: 2, unit: 'Days' }],
    severity: 'medium',
    suggestedDepartment: 'Neurology',
    aiSummary: 'Recurring dizziness and loss of balance. Possible vertigo or inner ear infection. Check history of hypertension.',
    status: 'seen',
    notes: ['Patient is stable', 'Prescribed anti-vertigo medication'],
    admittedDate: new Date().toISOString(),
    allergies: [],
    followUp: { date: new Date(Date.now() + 604800000).toISOString(), status: 'sent', type: 'routine' }
  },
  {
    id: 'P-103',
    name: 'Priya Patel',
    age: 29,
    gender: 'Female',
    phone: '555-0125',
    complaints: [{ symptom: 'High fever', duration: 3, unit: 'Days' }],
    severity: 'high',
    suggestedDepartment: 'General',
    aiSummary: 'Persistent fever of 39.5°C not responding to paracetamol. Signs of dehydration. Rule out Dengue or viral infection.',
    status: 'waiting',
    notes: [],
    admittedDate: new Date().toISOString(),
    allergies: ['Sulfa Drugs'],
    followUp: { date: new Date(Date.now() + 172800000).toISOString(), status: 'scheduled', type: 'urgent' }
  },
  {
    id: 'P-104',
    name: 'Arjun Singh',
    age: 12,
    gender: 'Male',
    phone: '555-0126',
    complaints: [{ symptom: 'Fractured wrist', duration: 2, unit: 'Hours' }],
    severity: 'medium',
    suggestedDepartment: 'Orthopedics',
    aiSummary: 'Visible deformity in left wrist following a fall. X-Ray required immediately to confirm fracture type.',
    status: 'waiting',
    notes: ['Ice pack applied'],
    admittedDate: new Date().toISOString(),
    allergies: [],
    followUp: { date: new Date(Date.now() + 1209600000).toISOString(), status: 'scheduled', type: 'routine' }
  },
  {
    id: 'P-105',
    name: 'Sneha Gupta',
    age: 34,
    gender: 'Female',
    phone: '555-0127',
    complaints: [{ symptom: 'Migraine', duration: 1, unit: 'Weeks' }],
    severity: 'low',
    suggestedDepartment: 'Neurology',
    aiSummary: 'Chronic migraine headaches with photosensitivity. Evaluate stress factors and sleep patterns.',
    status: 'discharged',
    notes: [],
    admittedDate: new Date().toISOString(),
    allergies: ['NSAIDs'],
    followUp: { date: new Date(Date.now() - 86400000).toISOString(), status: 'missed', type: 'tele-consult' }
  },
];

// Multilingual Dictionary
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
    en: {
        // Sidebar
        dashboard: 'Dashboard',
        reception: 'Reception',
        triage: 'Triage',
        consultant: 'Patient Care',
        analysis: 'Document AI',
        pharmacy: 'Pharmacy',
        billing: 'Billing',
        staff: 'Staff Roster',
        cleaner: 'Tasks',
        settings: 'Settings',
        // Dashboard
        totalPatients: 'Total Patients Today',
        criticalAttention: 'Critical Attention',
        requiresAction: 'Requires immediate action',
        waitingRoom: 'Waiting Room',
        avgWait: 'Avg wait',
        checkIn: 'Check In',
        codeBlue: 'CODE BLUE',
        searchPatients: 'Search patients...',
        allStatus: 'All Status',
        waiting: 'Waiting',
        seen: 'Seen',
        admitted: 'Admitted',
        discharged: 'Discharged / Completed',
        activeTreatment: 'Active Treatment',
        hospitalResources: 'Hospital Resources & Staffing',
        bedOccupancy: 'ICU Bed Occupancy',
        crossDeptTasks: 'Cross-Department Tasks',
        followUpCenter: 'Patient Follow-up & Retention Center',
        viewAll: 'View All',
        lastSeen: 'Last seen',
        due: 'Due',
        remind: 'Remind',
        escalate: 'Escalate',
        scheduled: 'SCHEDULED',
        missed: 'MISSED',
        doctorsOnDuty: 'Doctors On Duty',
        notice: 'NOTICE'
    },
    hi: {
        // Sidebar
        dashboard: 'डैशबोर्ड',
        reception: 'रिसेप्शन',
        triage: 'ट्राइएज',
        consultant: 'रोगी देखभाल',
        analysis: 'दस्तावेज़ एआई',
        pharmacy: 'फार्मेसी',
        billing: 'बिलिंग',
        staff: 'कर्मचारी रोस्टर',
        cleaner: 'कार्य',
        settings: 'सेटिंग्स',
        // Dashboard
        totalPatients: 'कुल रोगी (आज)',
        criticalAttention: 'गंभीर ध्यान',
        requiresAction: 'तत्काल कार्रवाई आवश्यक',
        waitingRoom: 'प्रतीक्षा कक्ष',
        avgWait: 'औसत प्रतीक्षा',
        checkIn: 'चेक इन',
        codeBlue: 'कोड ब्लू',
        searchPatients: 'रोगी खोजें...',
        allStatus: 'सभी स्थितियाँ',
        waiting: 'प्रतीक्षा में',
        seen: 'देखा गया',
        admitted: 'भर्ती',
        discharged: 'छुट्टी / पूर्ण',
        activeTreatment: 'सक्रिय उपचार',
        hospitalResources: 'अस्पताल संसाधन ಮತ್ತು स्टाफ',
        bedOccupancy: 'आईसीयू बिस्तर',
        crossDeptTasks: 'अंतर-विभागीय कार्य',
        followUpCenter: 'रोगी फॉलो-अप केंद्र',
        viewAll: 'सभी देखें',
        lastSeen: 'अंतिम बार देखा',
        due: 'नियत',
        remind: 'याद दिलाएं',
        escalate: 'बढ़ावा दें',
        scheduled: 'निर्धारित',
        missed: 'छूटा हुआ',
        doctorsOnDuty: 'ड्यूटी पर डॉक्टर',
        notice: 'सूचना'
    },
    kn: {
        // Sidebar
        dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        reception: 'ಸ್ವಾಗತ ಕಚೇರಿ',
        triage: 'ಚಿಕಿತ್ಸಾ ಆದ್ಯತೆ',
        consultant: 'ರೋಗಿ ಆರೈಕೆ',
        analysis: 'ದಸ್ತಾವೇಜು AI',
        pharmacy: 'ಔಷಧಾಲಯ',
        billing: 'ಬಿಲ್ಲಿಂಗ್',
        staff: 'ಸಿಬ್ಬಂದಿ ಪಟ್ಟಿ',
        cleaner: 'ಕಾರ್ಯಗಳು',
        settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        // Dashboard
        totalPatients: 'ಒಟ್ಟು ರೋಗಿಗಳು',
        criticalAttention: 'ತುರ್ತು ಗಮನ',
        requiresAction: 'ತಕ್ಷಣದ ಕ್ರಮ ಅಗತ್ಯವಿದೆ',
        waitingRoom: 'ಕಾಯುವ ಕೋಣೆ',
        avgWait: 'ಸರಾಸರಿ ಕಾಯುವಿಕೆ',
        checkIn: 'ದಾಖಲಾತಿ',
        codeBlue: 'ಕೋಡ್ ಬ್ಲೂ',
        searchPatients: 'ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ...',
        allStatus: 'ಎಲ್ಲಾ ಹಂತಗಳು',
        waiting: 'ಕಾಯುತ್ತಿದ್ದಾರೆ',
        seen: 'ನೋಡಲಾಗಿದೆ',
        admitted: 'ದಾಖಲಿಸಲಾಗಿದೆ',
        discharged: 'ಬಿಡುಗಡೆ / ಪೂರ್ಣಗೊಂಡಿದೆ',
        activeTreatment: 'ಸಕ್ರಿಯ ಚಿಕಿತ್ಸೆ',
        hospitalResources: 'ಆಸ್ಪತ್ರೆ ಸಂಪನ್ಮೂಲಗಳು',
        bedOccupancy: 'ಐಸಿಯು ಹಾಸಿಗೆ ಭರ್ತಿ',
        crossDeptTasks: 'ಅಂತರ-ವಿಭಾಗೀಯ ಕಾರ್ಯಗಳು',
        followUpCenter: 'ರೋಗಿ ಅನುಸರಣಾ ಕೇಂದ್ರ',
        viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
        lastSeen: 'ಕೊನೆಯದಾಗಿ ನೋಡಿದ್ದು',
        due: 'ಬಾಕಿ',
        remind: 'ಜ್ಞಾಪಿಸಿ',
        escalate: 'ಮೇಲಧಿಕಾರಿಗೆ ತಿಳಿಸಿ',
        scheduled: 'ನಿಗದಿಪಡಿಸಲಾಗಿದೆ',
        missed: 'ತಪ್ಪಿಹೋಗಿದೆ',
        doctorsOnDuty: 'ಕರ್ತವ್ಯದಲ್ಲಿರುವ ವೈದ್ಯರು',
        notice: 'ಸೂಚನೆ'
    }
};
